mappings:
  IsNullFilter: SilverstripeAustralia\AdvancedReports\Filters\IsNullFilter
  ScheduledAdvancedReportExtension: SilverstripeAustralia\AdvancedReports\Extensions\ScheduledAdvancedReportExtension
  ScheduledReportExtension: SilverstripeAustralia\AdvancedReports\Extensions\ScheduledReportExtension
  ReportFormatter: SilverstripeAustralia\AdvancedReports\Formatters\ReportFormatter
  SecondsToHoursFormatter: SilverstripeAustralia\AdvancedReports\Formatters\SecondsToHoursFormatter
  ReportFieldFormatter: SilverstripeAustralia\AdvancedReports\Formatters\ReportFieldFormatter
  HtmlReportFormatter: SilverstripeAustralia\AdvancedReports\Formatters\HtmlReportFormatter
  CsvReportFormatter: SilverstripeAustralia\AdvancedReports\Formatters\CsvReportFormatter
  DecimalHoursFormatter: SilverstripeAustralia\AdvancedReports\Formatters\DecimalHoursFormatter
  FullDateFromTimestampFormatter: SilverstripeAustralia\AdvancedReports\Formatters\FullDateFromTimestampFormatter
  DateFromTimestampFormatter: SilverstripeAustralia\AdvancedReports\Formatters\DateFromTimestampFormatter
  ScheduledReportJob: SilverstripeAustralia\AdvancedReports\Jobs\ScheduledReportJob
  AdvancedReportsService: SilverstripeAustralia\AdvancedReports\Services\AdvancedReportsService
  AdvancedReportsServiceInterface: SilverstripeAustralia\AdvancedReports\Services\AdvancedReportsServiceInterface
  AdvancedReport: SilverstripeAustralia\AdvancedReports\Models\AdvancedReport
  ConditionFilters: SilverstripeAustralia\AdvancedReports\Models\ConditionFilters
  AdvancedReportOutput: SilverstripeAustralia\AdvancedReports\Models\AdvancedReportOutput
  CombinedReport: SilverstripeAustralia\AdvancedReports\Models\CombinedReport
  DataObjectReport: SilverstripeAustralia\AdvancedReports\Models\DataObjectReport
  RelatedReport: SilverstripeAustralia\AdvancedReports\Models\RelatedReport
  FreeformReport: SilverstripeAustralia\AdvancedReports\Models\FreeformReport
  ReportPage: SilverstripeAustralia\AdvancedReports\Pages\ReportPage
  ReportPage_Controller: SilverstripeAustralia\AdvancedReports\Pages\ReportPageController
  ReportHolder: SilverstripeAustralia\AdvancedReports\Pages\ReportHolder
  ReportHolder_Controller: SilverstripeAustralia\AdvancedReports\Pages\ReportHolderController
  AdvancedReportsAdmin: SilverstripeAustralia\AdvancedReports\Admin\AdvancedReportsAdmin
  AdvancedReportsAdminItemRequest: SilverstripeAustralia\AdvancedReports\Admin\AdvancedReportsAdminItemRequest
